name: masked_bugs
description: A small example project showcasing bugs related to the
  mask_text_input_formatter package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  equatable: 2.0.3
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  mask_text_input_formatter: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
